<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="08a598b6-5c5a-43f3-9395-99e365b95bb1" name="dennis@SERVER 2015-05-27 23:13:30" runUser="VENDJUUREN\dennis" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2006">
  <TestRunConfiguration name="Local Test Run" id="b764eab8-ff7e-4592-8690-2360f6019acd">
    <Description>This is a default test run configuration for a local test run.</Description>
    <Deployment runDeploymentRoot="E:\Old mirror 05-01-13\Development\Projects\devc#2008\Domotica\TestResults\dennis_SERVER 2015-05-27 23_13_30">
      <DeploymentItem filename="E:\Old mirror 05-01-13\Development\Projects\devc#2008\VendjuurenLibrary\bin\Debug\Vendjuuren.Library.dll" />
      <DeploymentItem filename="E:\Old mirror 05-01-13\Development\Projects\devc#2008\Domotica\DomoticaLibrary\bin\Debug\Vendjuuren.Domotica.Library.dll" />
      <DeploymentItem filename="E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\bin\Debug\Vendjuuren.SQL.dll" />
    </Deployment>
    <TestTypeSpecific />
  </TestRunConfiguration>
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="SERVER" outcome="Error" timestamp="2015-05-27T23:14:03.6140000+02:00">
        <Text>One of the background threads threw exception: System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at Vendjuuren.SQL.Statement.Execute(ExceptionIgnoreCollection exceptions) in E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\Statement.cs:line 112
   at Vendjuuren.SQL.Statement.Execute() in E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\Statement.cs:line 76
   at Vendjuuren.SQL.Record.Save() in E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\Record.cs:line 77
   at Vendjuuren.SQL.Log.Save() in E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\Log.cs:line 48
   at Vendjuuren.SQL.Log..ctor(LogType type, LogAction action, String details) in E:\Old mirror 05-01-13\Development\Projects\devc#2008\SQL\Log.cs:line 31
   at Vendjuuren.Domotica.Library.TcpServerHelperClass._tcpServer_OnConnected(IntPtr handle, IPEndPoint iPEndPoint) in E:\Old mirror 05-01-13\Development\Projects\devc#2008\Domotica\DomoticaLibrary\TcpHelperClass.cs:line 75
   at Vendjuuren.Library.Network.TcpServer.OnClientConnect(IAsyncResult asyn) in E:\Old mirror 05-01-13\Development\Projects\devc#2008\VendjuurenLibrary\Network\TcpServer.cs:line 80
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.Socket.AcceptCallback(Object nullState)
   at System.Net.Sockets.Socket.RegisteredWaitCallback(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)</Text>
      </RunInfo>
      <RunInfo computerName="SERVER" outcome="Error" timestamp="2015-05-27T23:14:10.2260000+02:00">
        <Text>Test host process exited unexpectedly.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <Times creation="2015-05-27T23:13:30.4570000+02:00" queuing="2015-05-27T23:13:39.4480000+02:00" start="2015-05-27T23:13:39.6360000+02:00" finish="2015-05-27T23:14:10.2270000+02:00" />
  <TestDefinitions>
    <UnitTest name="ClientSendMessageTest" storage="e:\old mirror 05-01-13\development\projects\devc#2008\domotica\domoticatest\bin\debug\domoticatest.dll" id="78fe5d3b-84ba-ccb7-8319-d09cdb691e77">
      <Css projectStructure="" iteration="" />
      <Owners>
        <Owner name="" />
      </Owners>
      <Execution id="536682d2-303d-4969-ac0e-6feeede5c96f" />
      <TestMethod codeBase="E:\Old mirror 05-01-13\Development\Projects\devc#2008\Domotica\DomoticaTest\bin\Debug\DomoticaTest.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="DomoticaTest.TcpTest, DomoticaTest" name="ClientSendMessageTest" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="78fe5d3b-84ba-ccb7-8319-d09cdb691e77" executionId="48842a06-7e76-44c1-919d-25f6feaa213c" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="48842a06-7e76-44c1-919d-25f6feaa213c" testId="78fe5d3b-84ba-ccb7-8319-d09cdb691e77" testName="ClientSendMessageTest" computerName="SERVER" duration="00:00:30.4420000" startTime="2015-05-27T23:13:39.7850000+02:00" endTime="2015-05-27T23:14:10.2270000+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d">
    </UnitTestResult>
  </Results>
</TestRun>